IDIR =../include
CC=gcc
CFLAGS=-I$(IDIR) -fsanitize=address	-fsanitize=undefined -O0	-g
#-fsanitize=address	-fsanitize=undefined
ODIR=obj
LDIR =../lib

LIBS=-lm

_DEPS = cycledetection.h linked_list.h vertex.h graph.h
DEPS = $(patsubst %,$(IDIR)/%,$(_DEPS))

_OBJ = cycledetection.o linked_list.o graph.o main.o
OBJ = $(patsubst %,$(ODIR)/%,$(_OBJ))


$(ODIR)/%.o: %.c $(DEPS)
	$(CC) -c -o $@ $< $(CFLAGS)

program: $(OBJ)
	gcc -o $@ $^ $(CFLAGS) $(LIBS)

.PHONY: clean

clean:
	rm -f $(ODIR)/*.o *~ core $(INCDIR)/*~ program
